/*
 * This source file was generated by the Gradle 'init' task
 */
package com.courtesilol;

import com.courtesilol.view.MainView;

public class App {
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        MainView.launchApp(args);
        
    }

}
